webserver/experiment/urls.py
from django.urls import path
from django.views.generic.base import RedirectView

from . import views

app_name = 'experiment'
urlpatterns = [
    path('', views.welcome, name='index'),
    path('home', views.welcome, name='home'),
    path('welcome', views.welcome, name='welcome'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('consent_form', views.consent_form, name='consent_form'),
    path('demographics_survey', views.demographics_survey, name='demographics_survey'),
    path('paper_sample', views.paper_sample, name='paper_sample'),
    path('quiz_sample', views.quiz_sample, name='quiz_sample'),
    path('paper_1', views.paper_1, name='paper_1'),
    path('quiz_1', views.quiz_1, name='quiz_1'),
    path('paper_2', views.paper_2, name='paper_2'),
    path('quiz_2', views.quiz_2, name='quiz_2'),
    path('exit_survey', views.exit_survey, name='exit_survey'),
    path('finish', views.finish, name='finish'),
    path('logout', views.logout, name='logout'),
    path('<int:t>set_time', views.set_time, name='set_time'),
    path('switch_extensions', views.switch_extensions, name = 'switch_extensions')
]

webserver/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('experiment/', include('experiment.urls')),
    path('admin/', admin.site.urls),
]

webserver/experiment/models.py
from django.db import models
import datetime


class User(models.Model):
    #Primary key
    user_email = models.CharField(primary_key = True, max_length = 200)

    user_exten1 = models.IntegerField(choices = [(0, 0), (1, 1)])

    # User times
    user_t1 = models.TimeField(null = True)
    user_t2 = models.TimeField(null = True)
    user_t3 = models.TimeField(null = True)
    user_t4 = models.TimeField(null = True)
    user_t5 = models.TimeField(null = True)
    user_t6 = models.TimeField(null = True)

    def __str__(self):
        return self.user_email

class Authenticator(models.Model):
    user_id = models.OneToOneField(User, on_delete=models.CASCADE, unique=True)
    authenticator = models.CharField(max_length=255, primary_key=True)
    date_created = models.DateField(auto_now_add=True)

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=10000)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

webserver/experiment/forms.py
from django import forms

class CreateUserForm(forms.Form):
    participant_id = forms.IntegerField(label='Particpant ID', min_value=1, max_value=100, widget=forms.NumberInput(attrs={'class': 'form-control'}), required=False)

    def clean(self):
        cleaned_data = super().clean()
        if not cleaned_data['participant_id']:
            raise forms.ValidationError('You must enter a participant id.')

webserver/experiment/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from .models import Choice, Question, User, Authenticator
from .forms import CreateUserForm
from mysite import settings
from datetime import datetime
import random
import hmac
import os

def paper_s(request):
    return render(request,'experiment/paper_s.html')


def welcome(request):
    # if user is already authenticated redirect to sample paper page
    if request.COOKIES.get('auth'):
        return HttpResponseRedirect(reverse('experiment:consent_form'))

    if request.method == 'POST':
        # validate form
        form = CreateUserForm(request.POST)

        # if form is valid
        if form.is_valid():
            authenticator = None

            # sanitize participant id
            particpant_id = form.cleaned_data['participant_id']

            # attempt to create new user in db
            try:
                User.objects.create(user_email=particpant_id, user_exten1=random.randint(0,1), user_t1 = datetime.now()).save()
                user = User.objects.get(user_email=particpant_id)

                # generate new authenticator
                authenticator = hmac.new(
                    key = settings.SECRET_KEY.encode('utf-8'),
                    msg = os.urandom(32),
                    digestmod = 'sha256',
                ).hexdigest()

                # create a new authenticator for the new user
                Authenticator.objects.create(user_id=user, authenticator=authenticator).save()
            except Exception as e:
                if 'authenticator' in str(e):
                    form.add_error(field=None, error="Internal error. Try again.")
                else:
                    form.add_error(field=None, error='Particpant ID: ' + str(particpant_id) + ' already exists.')
                return render(request, 'experiment/welcome.html', {'form': form})

            # if succussful, set auth cookie w/ 2 hour ttl
            response = HttpResponseRedirect(reverse('experiment:consent_form'))
            response.set_cookie('auth', authenticator, max_age=3600)
            return response
        else:
            return render(request, 'experiment/welcome.html', {'form': form})

    return render(request, 'experiment/welcome.html', {'form': CreateUserForm()})

def consent_form(request):
    # try to get the authenticator cookie
    auth = request.COOKIES.get('auth')

    # if the authenticator cookie wasn't set...
    if not auth:
        # send user to welcome page
        return HttpResponseRedirect(reverse('experiment:welcome'))

    authenticator = Authenticator.objects.get(authenticator=auth)
    context = {
        'participant_id' : authenticator.user_id.user_email
    }

    return render(request,'experiment/consent_form.html', context)

def demographics_survey(request):
    # try to get the authenticator cookie
    auth = request.COOKIES.get('auth')

    # if the authenticator cookie wasn't set...
    if not auth:
        # send user to welcome page
        return HttpResponseRedirect(reverse('experiment:welcome'))

    authenticator = Authenticator.objects.get(authenticator=auth)
    context = {
        'participant_id' : authenticator.user_id.user_email
    }

    return render(request, 'experiment/surveys/demographics_survey.html', context)

def paper_sample(request):
    # try to get the authenticator cookie
    auth = request.COOKIES.get('auth')

    # if the authenticator cookie wasn't set...
    if not auth:
        # send user to welcome page
        return HttpResponseRedirect(reverse('experiment:welcome'))

    authenticator = Authenticator.objects.get(authenticator=auth)
    context = {
        'participant_id' : authenticator.user_id.user_email
    }

    return render(request, 'experiment/paper_sample.html', context)

def quiz_sample(request):
    # try to get the authenticator cookie
    auth = request.COOKIES.get('auth')

    # if the authenticator cookie wasn't set...
    if not auth:
        # send user to welcome page
        return HttpResponseRedirect(reverse('experiment:welcome'))

    authenticator = Authenticator.objects.get(authenticator=auth)
    context = {
        'participant_id' : authenticator.user_id.user_email
    }

    return render(request,'experiment/quizzes/quiz_sample.html', context)

def switch_extensions(request):
    # try to get the authenticator cookie
    auth = request.COOKIES.get('auth')

    # if the authenticator cookie wasn't set...
    if not auth:
        # send user to welcome page
        return HttpResponseRedirect(reverse('experiment:welcome'))


    authenticator = Authenticator.objects.get(authenticator=auth)
    user = authenticator.user_id


    context = {
        'participant_id' : user.user_email
    }

    context['paper_1'] = False if user.user_t2 else True

    if not user.user_exten1 and user.user_t2 or user.user_exten1 and not user.user_t2:
        return render(request,'experiment/holder_exten_0.html', context)
    else:
        return render(request,'experiment/holder_exten_1.html', context)


def paper_1(request):
    # try to get the authenticator cookie
    auth = request.COOKIES.get('auth')

    # if the authenticator cookie wasn't set...
    if not auth:
        # send user to welcome page
        return HttpResponseRedirect(reverse('experiment:welcome'))

    authenticator = Authenticator.objects.get(authenticator=auth)
    user = authenticator.user_id
    user.user_t1 = datetime.now()
    user.save()

    context = {
        'participant_id' : user.user_email
    }

    return render(request,'experiment/paper_1.html',context)

def paper_2(request):
    # try to get the authenticator cookie
    auth = request.COOKIES.get('auth')

    # if the authenticator cookie wasn't set...
    if not auth:
        # send user to welcome page
        return HttpResponseRedirect(reverse('experiment:welcome'))

    authenticator = Authenticator.objects.get(authenticator=auth)
    user = authenticator.user_id
    user.user_t3 = datetime.now()
    user.save()

    context = {
        'participant_id' : user.user_email
    }

    return render(request,'experiment/paper_2.html',context)

def quiz_s(request):
    return render(request,'experiment/quiz_s.html')

def quiz_1(request):
    # try to get the authenticator cookie
    auth = request.COOKIES.get('auth')

    # if the authenticator cookie wasn't set...
    if not auth:
        # send user to welcome page
        return HttpResponseRedirect(reverse('experiment:welcome'))

    authenticator = Authenticator.objects.get(authenticator=auth)
    user = authenticator.user_id
    user.user_t2 = datetime.now()
    user.save()

    context = {
        'participant_id' : user.user_email
    }

    return render(request,'experiment/quizzes/quiz_1.html', context)

def quiz_2(request):
    # try to get the authenticator cookie
    auth = request.COOKIES.get('auth')

    # if the authenticator cookie wasn't set...
    if not auth:
        # send user to welcome page
        return HttpResponseRedirect(reverse('experiment:welcome'))

    authenticator = Authenticator.objects.get(authenticator=auth)
    user = authenticator.user_id
    user.user_t4 = datetime.now()
    user.save()

    context = {
        'participant_id' : user.user_email
    }

    return render(request,'experiment/quizzes/quiz_2.html', context)

def exit_survey(request):
    # try to get the authenticator cookie
    auth = request.COOKIES.get('auth')

    # if the authenticator cookie wasn't set...
    if not auth:
        # send user to welcome page
        return HttpResponseRedirect(reverse('experiment:welcome'))

    authenticator = Authenticator.objects.get(authenticator=auth)
    user = authenticator.user_id
    user.user_t5 = datetime.now()
    user.save()

    context = {
        'participant_id' : user.user_email
    }

    return render(request, 'experiment/surveys/exit_survey.html', context)

def finish(request):
    # try to get the authenticator cookie
    auth = request.COOKIES.get('auth')

    # if the authenticator cookie wasn't set...
    if not auth:
        # send user to welcome page
        return HttpResponseRedirect(reverse('experiment:welcome'))

    authenticator = Authenticator.objects.get(authenticator=auth)
    context = {
        'participant_id' : authenticator.user_id.user_email
    }

    return render(request, 'experiment/finish.html', context)

def logout(request):
    # try to get the authenticator cookie
    auth = request.COOKIES.get('auth')

    # if the authenticator cookie wasn't set...
    if not auth:
        # send user to welcome page
        return HttpResponseRedirect(reverse('experiment:welcome'))

    # remove user's authenticator
    Authenticator.objects.get(authenticator=auth).delete()

    # remove 'auth' cookie and send to welcome page
    response = HttpResponseRedirect(reverse('experiment:welcome'))
    response.delete_cookie('auth')
    return response



class IndexView(generic.ListView):
    template_name = 'experiment/old_stuff/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'experiment/old_stuff/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'experiment/old_stuff/results.html'



def vote(request, question_id):

webserver/experiment/templates/experiment/consent_form.html
{% extends "experiment/paper_base.html" %}

{% block title} Consent Form {%endblock}

{% block user %}Participant #{{ participant_id }}{% endblock %}

{% block paper %}Consent Form{% endblock %}

{% block button %}
    <a class="btn btn-outline-light" href="{% url 'experiment:demographics_survey' %}">Agree</a>
{% endblock %}

{% block content %}
<iframe src="https://docs.google.com/document/d/e/2PACX-1vTQbi43trwCig3EoPiM9t7tYEeH5LmzI5IP2sUk6ywznf-BhPP5iz5UtBR1QCeYog/pub?embedded=true" height="1080"></iframe>
{% endblock %}

webserver/experiment/templates/experiment/finish.html
{% extends "experiment/paper_base.html" %}

{% block title} Thank You! {%endblock}

{% block user %}Participant #{{ participant_id }}{% endblock %}

{% block paper %}{% endblock %}

{% block button %}{% endblock %}

{% block content %}
<h1>Thank You!</h1>
<button id='logout' onclick="location.href = '{% url 'experiment:logout' %}'" style="width: 200px; height: 75px; margin-left: 38%">Exit</button>

{% endblock %}

webserver/experiment/templates/experiment/holder_exten_0.html
{% extends "experiment/paper_base.html" %}

{% block title} Extension Switch {%endblock}

{% block user %}Participant #{{ participant_id }}{% endblock %}

{% block paper %}Extension Switch{% endblock %}

{% block button %}
{% if paper_1 %}
    <a class="btn btn-outline-light" href="{% url 'experiment:paper_1' %}">Begin</a>
{% else %}
<a class="btn btn-outline-light" href="{% url 'experiment:paper_2' %}">Begin</a>
{% endif %}
{% endblock %}

{% block content %}
<div class = 'holder'>
              Please deactivate extension A, and ensure that extension B is activated. Please ask your coordinator if you would like assistance or clarification.
</div>
{% endblock %}

webserver/experiment/templates/experiment/holder_exten_1.html
{% extends "experiment/paper_base.html" %}

{% block title} Extension Switch {%endblock}

{% block user %}Participant #{{ participant_id }}{% endblock %}

{% block paper %}Extension Switch{% endblock %}

{% block button %}
{% if paper_1 %}
    <a class="btn btn-outline-light" href="{% url 'experiment:paper_1' %}">Begin</a>
{% else %}
<a class="btn btn-outline-light" href="{% url 'experiment:paper_2' %}">Begin</a>
{% endif %}
{% endblock %}

{% block content %}
<div class = 'holder'>
              Please deactivate extension B, and ensure that extension A is activated. Please ask your coordinator if you would like assistance or clarification.
</div>
{% endblock %}

webserver/experiment/templates/experiment/paper_1.html
{% extends "experiment/paper_base.html" %}
{% load static %}


{% block title} Paper 1 {%endblock}

{% block user %}Participant #{{ participant_id }}{% endblock %}

{% block paper %}Paper 1{% endblock %}

{% block button %}
    <a class="btn btn-outline-light" href="{% url 'experiment:quiz_1' %}">Next</a>
{% endblock %}

{% block content %}
<h1> Frequency Diffeomorphisms for Efficient Image Registration </h1>

<div class = "Authors">Miaomiao Zhang, Ruizhi Liao, Adrian V. Dalca, Esra A. Turk, Jie Luo, P. Ellen Grant, and Polina Golland </div>

<figure>
  <img id = "figure", src = "../../static/experiment/images/paper_2_image.png"/>
  <figcaption> Left: average optimal energy for different values of the truncated dimension n = 8, 16, . . . , 128. Right: example propagated segmentation with 35 structures obtained by our method. 2D slices are shown for visualization only, all computations are carried out fully in 3D.</figcaption>
</figure>

<h3> Abstract </h3>
<div class = "paragraph"> This paper presents an efficient algorithm for large deformation diffeomorphic metric mapping (LDDMM) with geodesic shooting for image registration. We introduce a novel finite dimensional Fourier representation of diffeomorphic deformations based on the key fact that the high frequency components of a diffeomorphism remain stationary throughout the integration process when computing the deformation associated with smooth velocity fields. We show that manipulating high dimensional diffeomorphisms can be carried out entirely in the bandlimited space by integrating the nonstationary low frequency components of the displacement field. This insight substantially reduces the computational cost of the registration problem. Experimental results show that our method is significantly faster than the state-of-the-art diffeomorphic image registration methods while producing equally accurate alignment. We demonstrate our algorithm in two different applications of image registration: neuroimaging and in-utero imaging. </div>

<h3> 1 Introduction </h3>

<div class = "paragraph"> Diffeomorphisms have been widely used in the field of image registration [6, 7], atlas-based image segmentation [4,10], and anatomical shape analysis [14, 22]. In this paper, we focus on a time-varying velocity field representation for diffeomorphisms as it supplies a distance metric that is critical to statistical analysis of anatomical shapes, for instance, by least squares, geodesic regression, or principal modes detection [13,16,22]. </div>
<br>
<div class = "paragraph"> In spite of the advantages of supporting Riemannian metrics in LDDMM, the extremely high computational cost and large memory footprint of the current implementations has limited the use of time-varying velocity representations in important applications that require computational efficiency. The original LDDMM optimization performs gradient decent on the entire time-varying velocity field that is defined on a dense image grid. Since a geodesic is uniquely determined by its initial conditions on the velocity field, the geodesic shooting algorithm has been shown to reduce the computational complexity and improve optimization landscape by manipulating the initial velocity via the geodesic evolution equations [20]. FLASH (finite dimensional Lie algebras for shooting) [23] is a recent variant of LDDMM with geodesic shooting that employs a low dimensional bandlimited representation of the initial velocity field to further improve the convergence and efficiency of the optimization. The algorithm still maps the velocity fields from the low dimensional Fourier space back to the full image domain to perform forward integration at each iteration [23]. The computational complexity of this step thus dominates the entire procedure of diffeomorphic image registration. </div>
<br>
<div class = "paragraph"> Previous works that aimed to improve diffeomorphic representations have reduced the high degrees of freedom available to represent the velocity fields, but not the diffeomorphisms themselves. In this paper, we adopt the low dimensional representation of the tangent space of diffeomorphisms [23] and propose an efficient way to compute diffeomorphisms in the bandlimited space, thus further reducing the computational complexity of image registration. Our approach is based on the important insight that only the low frequency components of the diffeomorphisms vary over time when integrating a bandlimited velocity field to obtain the deformation. Since the optimization of image registration can be directly solved by advecting the inverse of diffeomorphisms [17], we propose a novel Fourier representation of the deformation in the inverse coordinate system that is computed entirely in the low dimensional bandlimited space. The theoretical tools developed in this paper are broadly applicable to other parametrization of diffeomorphic transformations, such as stationary velocity fields [2,3,19]. To evaluate the proposed algorithm, we perform image registration of real 3D MR images and show that the accuracy of the propagated segmentations is comparable to that obtained via the state-of-the-art diffeomorphic image registration methods, while the runtime and the memory demands are dramatically lower for our method. We demonstrate the method in the context of atlas-based segmentation of brain images and of temporal alignment of in-utero MRI scans.

{% endblock content%}

webserver/experiment/templates/experiment/paper_2.html
{% extends "experiment/paper_base.html" %}
{% load static %}

{% block title} Paper 2 {%endblock}

{% block user %}Particpant #{{ participant_id }}{% endblock %}

{% block paper %}Paper 2{% endblock %}

{% block button %}
    <a class="btn btn-outline-light" href="{% url 'experiment:quiz_2' %}">Next</a>
{% endblock %}

{% block content %}
<h1> p21 produces a bioactive secretome that places stressed cells under immunosurveillance </h1>
<figure>
  <img id = "figure", src = "../../static/experiment/images/paper_1_image.jpg"/>
  <figcaption> p21 places stressed cells under immunosurveillance. p21 induced by cells under duress activates an
    Rb-dependent transcriptional program that produces CXCL14 and other secreted factors. CXCL14 promptly
    recruits macrophages, which disengage if stressed cells recuperate and normalize p21 within 4 days.
    However, if p21 induction persists, the adjoined macrophages polarize toward an M1 phenotype and cytotoxic
    T cells arrive to eliminate target cells, including preneoplastic cells.</figcaption>
</figure>

<div class = "Authors"> Ines Sturmlechner, Cheng Zhang, Chance C. Sine, Erik-Jan van Deursen, Karthik B. Jeganathan,
Naomi Hamada, Jan Grasic, David Friedman, Jeremy T. Stutchman, Ismail Can, Masakazu Hamada,
Do Young Lim, Jeong-Heon Lee, Tamas Ordog, Remi-Martin Laberge, Virginia Shapiro,
Darren J. Baker, Hu Li, Jan M. van Deursen </div>


<h3> INTRODUCTION: </h3>

<div class="paragraph">
  Complex multicellular organisms are subject to a myriad of cellular stresses, which can be managed through cell-intrinsic adaptation and repair mechanisms. Cells that fail to recover activate programs that lead to regulated cell death or cellular senescence, thereby limiting the risk of neoplastic transformation. Evidence is emerging that intercellular communication also plays an important role in dealing with cellular stresses. For instance, cells experiencing DNA damage display cell-surface ligands that facilitate lymphocyte recognition and secrete cytokines that attract myeloid cells. Furthermore, cells undergoing cellular senescence generate a bioactive secretome known as the senescence-associated  secretory phenotype (SASP), which facilitates senescent cell (SNC) recognition by the immune system.
</div>

<h3> RATIONALE: </h3>

<div class="paragraph">
  Stressed cells that become senescent have been implicated in various biological processes beyond cancer, including development, tissue repair, aging, and age-related diseases, presumably through the paracrine actions of the SASP. To better understand the molecular properties of SNCs, we sought  to identify key determinants of SNC identity by screening for genes nearby senescence-associated super-enhancers conserved across stressors, cell types, and mammalian species. Through this approach, we identified p21 (Cdkn1a), which encodes the cyclin-dependent kinase (CDK) inhibitor p21, and conducted an in-depth analysis of its functions from the time cells first experience stress until they have become senescent.
</div>

<h3>RESULTS: </h3>

<div class="paragraph">
  We found that p21—in addition to its function in maintaining the cell-cycle arrest of SNCs—has a prominent role in establishing the SASP through retinoblastoma protein (Rb)–dependent transcription involving select SMAD and STAT transcription factors. Although this transcriptional program remains active in SNCs, p21 initiates this program as a first response to stress occurring in parallel with cell-cycle arrest. The resulting immediate-early secretome, which we term the p21-activated secretory phenotype (PASP), comprises several hundred factors, including the chemokine CXCL14, which recruits macrophages to surveil stressed cells with elevated p21. In mouse liver, these macrophages disengage if cells normalize p21 levels within 4 days after its induction. However, if p21 remains elevated, the adjoined macrophages polarize toward an M1 phenotype, and cytotoxic T lymphocytes arrive to execute target cell elimination when classical markers of senescence are not yet detectable. This scenario also occurs with oncogenic KRAS-mediated p21 induction, highlighting the physiological relevance of the uncovered immunosurveillance mechanism to tumor suppression. By contrast, CDK inhibitor p16, which is often elevated in SNCs and also halts cell-cycle progression through Rb hypo-phosphorylation, does not induce immunosurveillance when overexpressed in mouse liver. Although p16 induction yields an immediate-early secretome that consists largely of factors that overlap with the PASP, there are far fewer factors, and CXCL14 is absent. Studies on CDK inhibitor p27 further suggested that coordinated induction of cell-cycle arrest and immunosurveillance is a distinctive feature of p21.
</div>

<h3>CONCLUSION: </h3>
<div class="">
  Our study demonstrates that in response to cellular stress, p21 alters the transcription regulatory properties of Rb to not only inhibit genes required for cell-cycle progression but also activate a large collection of genes implicated in diverse biological functions, including immunosurveillance. By promptly recruiting macrophages to stressed cells, p21 sets a biological timer that allows for a period in which stressed cells can recuperate, thereby normalizing p21. This timer expires when the immune response transitions from a surveillance to a clearance mode. As such, p21 provides a first line of defense against dysfunctional cells that can become cancerous or otherwise cause pathology. Given that p21 is a p53 target gene, it will be important to define whether this p21-controlled immunoclearance mechanism is perturbed in cancer cells that lack functional p53, and if so, to explore the therapeutic impact of interventions that reactivate it.
</div>

{% endblock content%}

webserver/experiment/templates/experiment/paper_base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'experiment/style.css' %}">

    <title>{% block title %}Paper{% endblock %}</title>
</head>
<body class="bg-light">
  <nav class="navbar navbar-dark bg-primary fixed-top">
    <div class="container-fluid">
      <a class="navbar-brand text-white-50">{% block user %}Experiment {% endblock %}</a>
      <p class="mx-auto my-auto fs-5 text-light" style="text-align: center;">{% block paper %}{% endblock %}</p>
      <form class="d-flex">
        {% block button %}{% endblock %}
      </form>
    </div>
  </nav>
  <div class="container-fluid mb-2" style="padding-top: 65px;">
    <div class="row col-7 mx-auto border rounded bg-white">
      {% block content %}{% endblock %}
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

webserver/experiment/templates/experiment/paper_sample.html
{% extends "experiment/paper_base.html" %}
{% load static %}


{% block title %}Sample Paper{% endblock %}

{% block user %}Participant #{{ participant_id }}{% endblock %}

{% block paper %}Sample Paper{% endblock %}

{% block button %}
    <a class="btn btn-outline-light" href="{% url 'experiment:quiz_sample' %}">Next</a>
{% endblock %}

{% block content %}
<h1> Wikipedia Wikipedia page </h1>

<div class = "Authors"> Misc </div>
<figure>
  <img id = "figure", src = "../../static/experiment/images/paper_sample_image.jpg" width="341" height="312"/>
  <figcaption> Wikipedia logo</figcaption>
</figure>
<div class = "paragraph">
Wikipedia (/ˌwɪkɪˈpiːdiə/ wik-ih-PEE-dee-ə or /ˌwɪki-/ wik-ee-) is a free content, multilingual online encyclopedia written and maintained by a community of volunteers through a model of open collaboration, using a wiki-based editing system. Individual contributors, also called editors, are known as Wikipedians. It is the largest and most-read reference work in history,[3] and consistently one of the 15 most popular websites ranked by Alexa; as of 2021, Wikipedia was ranked the 13th most popular site.[3][4] A visitor spends an average time on Wikipedia of 3 minutes and 45 seconds each day.[5] It is hosted by the Wikimedia Foundation, an American non-profit organization funded mainly through small donations.[6]
</div>
<div class = "paragraph">
Wikipedia was launched on January 15, 2001, by Jimmy Wales[7] and Larry Sanger; Sanger coined its name as a blending of "wiki" and "encyclopedia".[8][9] Initially available only in English, versions in other languages were quickly developed. Its combined editions comprise more than 57 million articles, attracting around 2 billion unique device visits per month, and more than 17 million edits per month (1.9 edits per second).[10][11] In 2006, Time magazine stated that the policy of allowing anyone to edit had made Wikipedia the "biggest (and perhaps best) encyclopedia in the world", and is "a testament to the vision of one man, Jimmy Wales".[12]
</div>
<div class = "paragraph">
Wikipedia has received praise for its enablement of the democratization of knowledge, extent of coverage, unique structure, culture, and reduced amount of commercial bias, but criticism for exhibiting systemic bias, particularly gender bias against women and alleged ideological bias.[13][14] Its reliability was frequently criticized in the 2000s, but has improved over time and has been generally praised in the late 2010s and early 2020s.[3][13][15] Its coverage of controversial topics such as American politics and major events such as the COVID-19 pandemic has received substantial media attention. It has been censored by world governments, ranging from specific pages to the entire site. It has become an element of popular culture, with references in books, films and academic studies. In 2018, Facebook and YouTube announced that they would help users detect fake news by suggesting fact-checking links to related Wikipedia articles.[16][17]
</div>
{% endblock %}